"""Generate ENDPOINTS.md — CLI commands, Docker ports, and API surface."""

from __future__ import annotations

import logging
from pathlib import Path

from ..extractor.docker_parser import parse_services
from ..extractor.pyproject_parser import parse_pyproject

log = logging.getLogger(__name__)

OUTPUT_PATH = Path("docs/architecture/codemap/ENDPOINTS.md")


def render_endpoints(repo_root: Path, component_files: dict | None = None) -> str:
    pyproject_info = parse_pyproject(repo_root / "pyproject.toml")
    services = parse_services(repo_root / "docker-compose.yml")

    lines = [
        "# Endpoints Reference",
        "",
        "> Auto-generated by `make codemap`. Do not edit.",
        "> Source: `pyproject.toml` scripts, `docker-compose.yml`, AST CLI scan.",
        "",
    ]

    # --- CLI commands from pyproject.toml [project.scripts] ---
    lines += [
        "## CLI Commands (`[project.scripts]`)",
        "",
    ]
    if pyproject_info.scripts:
        lines.append("| Command | Entry point |")
        lines.append("|---------|-------------|")
        for cmd, entry in sorted(pyproject_info.scripts.items()):
            lines.append(f"| `{cmd}` | `{entry}` |")
    else:
        lines.append("*No scripts defined in pyproject.toml.*")

    # --- CLI commands from AST (click/typer decorators) ---
    if component_files:
        cli_entries: list[tuple[str, str]] = []
        for comp_id, files in component_files.items():
            for fm in files:
                for cmd in fm.cli_commands:
                    cli_entries.append((comp_id, cmd))

        if cli_entries:
            lines += [
                "",
                "## CLI Commands (detected from source)",
                "",
                "| Component | Command |",
                "|-----------|---------|",
            ]
            for comp_id, cmd in sorted(cli_entries):
                lines.append(f"| `{comp_id}` | `{cmd}` |")

    # --- Docker services ---
    lines += [
        "",
        "## Infrastructure Ports (`docker-compose.yml`)",
        "",
    ]
    if services:
        lines.append("| Service | Ports | Purpose |")
        lines.append("|---------|-------|---------|")
        _PURPOSE = {
            "postgres": "Relational store (facts, reflections, state)",
            "qdrant": "Vector search (experience retrieval)",
            "open-webui": "LLM chat UI",
            "ollama": "Local LLM server",
            "redis": "Cache / message broker",
        }
        for name, cfg in services.items():
            if not isinstance(cfg, dict):
                continue
            ports_raw = cfg.get("ports", [])
            ports = ", ".join(f"`{p}`" for p in ports_raw[:3]) if ports_raw else "—"
            purpose = next((v for k, v in _PURPOSE.items() if k in name.lower()), "—")
            lines.append(f"| `{name}` | {ports} | {purpose} |")
    else:
        lines.append("*No `docker-compose.yml` found or no services defined.*")

    # --- HTTP API (FastAPI) ---
    lines += [
        "",
        "## HTTP API",
        "",
        "FastAPI routes are defined in `src/atman/` (see `[api]` optional dependency).",
        "Run `uvicorn atman.api:app --reload` and open `/docs` for the interactive Swagger UI.",
        "",
    ]

    lines.append("")
    return "\n".join(lines)


def write_endpoints(repo_root: Path, component_files: dict | None = None) -> bool:
    """Write ENDPOINTS.md. Returns True if file changed."""
    output_path = repo_root / OUTPUT_PATH
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = render_endpoints(repo_root, component_files)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
        return False

    output_path.write_text(content, encoding="utf-8")
    log.info("Written %s", output_path)
    return True
