"""Generate STARTUP_DEPS.md from docker-compose.yml service information."""

from __future__ import annotations

import logging
from pathlib import Path

from ..extractor.docker_parser import parse_services

log = logging.getLogger(__name__)

OUTPUT_PATH = Path("docs/architecture/codemap/STARTUP_DEPS.md")


def render_startup_deps(repo_root: Path) -> str:
    compose = repo_root / "docker-compose.yml"
    services = parse_services(compose)

    lines = [
        "# Startup Dependencies",
        "",
        "> Auto-generated by `make codemap`. Do not edit.",
        "",
        "## Docker Compose Services",
        "",
    ]

    if not services:
        lines.append("*No `docker-compose.yml` found or no services defined.*")
    else:
        lines.append("| Service | Image | Ports | Depends On |")
        lines.append("|---------|-------|-------|------------|")
        for name, cfg in services.items():
            if not isinstance(cfg, dict):
                continue
            image = cfg.get("image", cfg.get("build", "*(build)*"))
            ports_raw = cfg.get("ports", [])
            ports = ", ".join(str(p) for p in ports_raw[:3]) if ports_raw else "—"
            depends = cfg.get("depends_on", [])
            if isinstance(depends, dict):
                depends = list(depends.keys())
            dep_str = ", ".join(f"`{d}`" for d in depends) if depends else "—"
            lines.append(f"| `{name}` | `{image}` | {ports} | {dep_str} |")

    lines += [
        "",
        "## Required Environment Variables",
        "",
        "See `src/atman/config.py` for the full list of Pydantic settings fields.",
        "Key variables:",
        "",
        "| Variable | Description | Default |",
        "|----------|-------------|---------|",
        "| `ATMAN_MEMORY_BACKEND` | Storage backend: `postgres\\|file\\|inmemory` | `file` |",
        "| `EMBEDDING_BACKEND` | Embedding: `ollama\\|flag\\|mock` | `ollama` |",
        "| `ATMAN_LLM_BASE_URL` | LLM endpoint (OpenAI-compatible) | — |",
        "| `ATMAN_OLLAMA_BASE_URL` | Ollama host | `http://localhost:11434` |",
        "| `DATABASE_URL` | PostgreSQL DSN (postgres backend) | — |",
        "",
    ]
    return "\n".join(lines)


def write_startup_deps(repo_root: Path) -> bool:
    """Write STARTUP_DEPS.md. Returns True if file changed."""
    output_path = repo_root / OUTPUT_PATH
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = render_startup_deps(repo_root)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
        return False

    output_path.write_text(content, encoding="utf-8")
    log.info("Written %s", output_path)
    return True
