"""Generate TEST_ENV.md describing the test environment setup."""

from __future__ import annotations

import logging
from pathlib import Path

log = logging.getLogger(__name__)

OUTPUT_PATH = Path("docs/architecture/codemap/TEST_ENV.md")

TEMPLATE = """\
# Test Environment

> Auto-generated by `make codemap`. Do not edit.

## Overview

All tests run without external services by default (in-memory adapters).
PostgreSQL / Ollama tests are skipped unless the relevant env var or marker is set.

## Test Markers

| Marker | Meaning | Skip condition |
|--------|---------|----------------|
| *(none)* | Unit test — no external deps | Always runs |
| `slow` | Long-running test | `-m "not slow"` |
| `integration` | Multiple real components, no mocks | Requires full stack |
| `e2e` | Full end-to-end scenario | Requires agent + LLM |
| `requires_ollama` | Needs a running Ollama instance | `OLLAMA_HOST` not set |
| `requires_llm` | Needs Atman's internal LLM | `ATMAN_LLM_BASE_URL` not set |
| `requires_agent_llm` | Needs the agent's LLM | `AGENT_LLM_BASE_URL` not set |

## Running Tests

```bash
# Full suite (CI style)
uv run pytest tests/ -v --cov=atman --cov-fail-under=90

# Fast (skip slow tests)
uv run pytest tests/ -m "not slow" -v

# Integration only
uv run pytest tests/ -m "integration" -v

# Single file
uv run pytest tests/path/to/test_foo.py -v
```

## Coverage

Minimum coverage gate: **89%** (temporarily lowered from 90%; see `pyproject.toml`).
Coverage source: `src/atman/`.
Several files are excluded from coverage (CLI entry points, Postgres adapters requiring DB, heavy ML adapters).

## In-Memory Adapters Used in Tests

| Adapter | Implements |
|---------|-----------|
| `InMemoryBackend` | `FactualMemory` |
| `InMemoryStateStore` | `StateStore` |
| `InMemoryEntityRegistry` | `EntityRegistry` |
| `InMemoryMaintenanceQueue` | `MaintenanceQueue` |
| `InMemoryMemoryGuardian` | `MemoryGuardian` |
| `MockEmbeddingAdapter` | `EmbeddingPort` |
| `MockReflectionModel` | `ReflectionModel` |
| `NoOpLinguisticAnalyzer` | `LinguisticAnalyzer` |
| `NoOpReranker` | `MemoryReranker` |
"""


def write_test_env(repo_root: Path) -> bool:
    """Write TEST_ENV.md. Returns True if file changed."""
    output_path = repo_root / OUTPUT_PATH
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if output_path.exists() and output_path.read_text(encoding="utf-8") == TEMPLATE:
        return False

    output_path.write_text(TEMPLATE, encoding="utf-8")
    log.info("Written %s", output_path)
    return True
