"""Generate UNDOCUMENTED.md listing public classes/functions without docstrings."""

from __future__ import annotations

import contextlib
import logging
from pathlib import Path

from ..extractor.ast_walker import FileMetadata

log = logging.getLogger(__name__)

OUTPUT_PATH = Path("docs/architecture/codemap/UNDOCUMENTED.md")


def render_undocumented(
    component_files: dict[str, list[FileMetadata]],
    repo_root: Path,
) -> str:
    lines = [
        "# Undocumented Public API",
        "",
        "> Auto-generated by `make codemap`. Do not edit.",
        "> Lists public classes without docstrings.",
        "",
    ]

    any_found = False
    for comp_id, files in component_files.items():
        undoc = []
        for fm in files:
            for cls in fm.public_classes:
                if not cls.docstring:
                    rel = Path(fm.path)
                    with contextlib.suppress(ValueError):
                        rel = rel.relative_to(repo_root / "src" / "atman")
                    undoc.append((rel.as_posix(), cls.name))

        if undoc:
            any_found = True
            lines.append(f"## `{comp_id}`")
            lines.append("")
            lines.append("| File | Class |")
            lines.append("|------|-------|")
            for fpath, cname in undoc:
                lines.append(f"| `{fpath}` | `{cname}` |")
            lines.append("")

    if not any_found:
        lines.append("*All public classes have docstrings.*")

    return "\n".join(lines)


def write_undocumented(
    component_files: dict[str, list[FileMetadata]],
    repo_root: Path,
) -> bool:
    """Write UNDOCUMENTED.md. Returns True if file changed."""
    output_path = repo_root / OUTPUT_PATH
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = render_undocumented(component_files, repo_root)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
        return False

    output_path.write_text(content, encoding="utf-8")
    log.info("Written %s", output_path)
    return True
